### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by malte-v** [google/cel-cpp#44]
I hesistate to ask, but can you give me a minimal example of how to evaluate an expression with a set of input values? Build instructions would also be great. Thanks in advance!

**Comment by kyessenov** [comment]
Thanks for your interest. I suggest taking a look at the benchmark functions in https://github.com/google/cel-cpp/blob/master/eval/tests/benchmark_test.cc#L598. They are self-contained and show various ways to express the same condition (using top-level bindings, maps, and protos).

We rely on Bazel as a build system. You can use Bazelisk (https://github.com/bazelbuild/bazelisk) for a user-friendly starter script, which will pick the right version of bazel.

**Comment by malte-v** [comment]
Thank you for your help. I'm trying to write a "black box" library that takes a CEL expression and a JSON object with identifier/value pairs and outputs the result (or a detailed error, if there is one). The README of `cel-go` said the library has "first-class support for JSON". Is this also the case for `cel-cpp`? Do I need to manually map the JSON types to CEL types? Could you show me the easiest way to accomplish my goal? Thanks!

**Comment by malte-v** [comment]
Ok, so I've run `bazel build //...` and now I have a ton of output files. All I really need is something resembling the test function you showed me and I'd like to know:

- Where to find the required headers
- What objects I need to link against

I'd prefer to keep bazel out of my project because it's primarily written in Rust and I just need a single C function that evaluates a CEL expression.

**Comment by kyessenov** [comment]
Regarding the JSON support, you can store protobuf Struct as a message value in the activation. Protobuf struct is literally a JSON object. You might need to apply some type conversions in function applications since JSON is untyped.

You can use cel-go to convert a syntactic CEL expression to a protobuf form. It's just a protobuf, so you can serialize it as binary or JSON. Alternatively, this project now has its own parser which is identical to cel-go parser. It just got pushed out, so I haven't tried it myself, but there are plenty of tests in `parser` sub-directory that should give you an idea how to use it.

**Comment by malte-v** [comment]
I've figured everything out now. Thanks for your help.
